export type Theme = 'slate' | 'light' | 'sky' | 'rose';

export type ThemeVariables = {
  '--color-bg': string;
  '--color-surface-1': string;
  '--color-surface-2': string;
  '--color-surface-3': string;
  '--color-surface-inset': string;
  '--color-text-primary': string;
  '--color-text-secondary': string;
  '--color-text-tertiary': string;
  '--color-text-placeholder': string;
  '--color-border': string;
  '--color-primary': string;
  '--color-primary-hover': string;
  '--color-primary-focus': string;
  '--color-primary-text': string;
  '--color-secondary': string;
  '--color-success': string;
  '--color-success-hover': string;
  '--color-danger': string;
  '--color-warning-border': string;
  '--color-warning-bg': string;
  '--color-warning-text': string;
  '--color-quota-border': string;
  '--color-quota-bg': string;
  '--color-quota-text': string;
  '--color-error-border': string;
  '--color-error-bg': string;
  '--color-error-text': string;
  '--color-info-border': string;
  '--color-info-bg': string;
  '--color-info-text': string;
  '--gradient-from': string;
  '--gradient-to': string;
};

export const themes: Record<Theme, ThemeVariables> = {
  slate: {
    '--color-bg': '#0f172a',
    '--color-surface-1': '#1e293b',
    '--color-surface-2': '#334155',
    '--color-surface-3': '#475569',
    '--color-surface-inset': '#020617',
    '--color-text-primary': '#f1f5f9',
    '--color-text-secondary': '#cbd5e1',
    '--color-text-tertiary': '#94a3b8',
    '--color-text-placeholder': '#64748b',
    '--color-border': '#334155',
    '--color-primary': '#14b8a6',
    '--color-primary-hover': '#0d9488',
    '--color-primary-focus': '#14b8a6',
    '--color-primary-text': '#ffffff',
    '--color-secondary': '#0ea5e9',
    '--color-success': '#22c55e',
    '--color-success-hover': '#16a34a',
    '--color-danger': '#ef4444',
    '--color-warning-border': '#f59e0b',
    '--color-warning-bg': '#b45309',
    '--color-warning-text': '#fef3c7',
    '--color-quota-border': '#f97316',
    '--color-quota-bg': '#c2410c',
    '--color-quota-text': '#ffedd5',
    '--color-error-border': '#dc2626',
    '--color-error-bg': '#991b1b',
    '--color-error-text': '#fecaca',
    '--color-info-border': '#14b8a6',
    '--color-info-bg': '#115e59',
    '--color-info-text': '#ccfbf1',
    '--gradient-from': '#f1f5f9',
    '--gradient-to': '#5eead4',
  },
  light: {
    '--color-bg': '#f1f5f9',
    '--color-surface-1': '#ffffff',
    '--color-surface-2': '#f1f5f9',
    '--color-surface-3': '#e2e8f0',
    '--color-surface-inset': '#e2e8f0',
    '--color-text-primary': '#0f172a',
    '--color-text-secondary': '#334155',
    '--color-text-tertiary': '#64748b',
    '--color-text-placeholder': '#94a3b8',
    '--color-border': '#e2e8f0',
    '--color-primary': '#0d9488',
    '--color-primary-hover': '#0f766e',
    '--color-primary-focus': '#0d9488',
    '--color-primary-text': '#ffffff',
    '--color-secondary': '#0284c7',
    '--color-success': '#16a34a',
    '--color-success-hover': '#15803d',
    '--color-danger': '#dc2626',
    '--color-warning-border': '#f59e0b',
    '--color-warning-bg': '#fffbeb',
    '--color-warning-text': '#b45309',
    '--color-quota-border': '#f97316',
    '--color-quota-bg': '#fff7ed',
    '--color-quota-text': '#c2410c',
    '--color-error-border': '#dc2626',
    '--color-error-bg': '#fee2e2',
    '--color-error-text': '#991b1b',
    '--color-info-border': '#0d9488',
    '--color-info-bg': '#f0fdfa',
    '--color-info-text': '#115e59',
    '--gradient-from': '#0f172a',
    '--gradient-to': '#0d9488',
  },
  sky: {
    '--color-bg': '#0c1429',
    '--color-surface-1': '#0a1936',
    '--color-surface-2': '#1e3a5f',
    '--color-surface-3': '#2d568c',
    '--color-surface-inset': '#020a1a',
    '--color-text-primary': '#e0f2fe',
    '--color-text-secondary': '#bae6fd',
    '--color-text-tertiary': '#7dd3fc',
    '--color-text-placeholder': '#38bdf8',
    '--color-border': '#1e3a5f',
    '--color-primary': '#38bdf8',
    '--color-primary-hover': '#0ea5e9',
    '--color-primary-focus': '#38bdf8',
    '--color-primary-text': '#0c1429',
    '--color-secondary': '#0ea5e9', // Re-using for now
    '--color-success': '#22c55e',
    '--color-success-hover': '#16a34a',
    '--color-danger': '#ef4444',
    '--color-warning-border': '#f59e0b',
    '--color-warning-bg': '#b45309',
    '--color-warning-text': '#fef3c7',
    '--color-quota-border': '#f97316',
    '--color-quota-bg': '#c2410c',
    '--color-quota-text': '#ffedd5',
    '--color-error-border': '#dc2626',
    '--color-error-bg': '#991b1b',
    '--color-error-text': '#fecaca',
    '--color-info-border': '#14b8a6',
    '--color-info-bg': '#115e59',
    '--color-info-text': '#ccfbf1',
    '--gradient-from': '#e0f2fe',
    '--gradient-to': '#7dd3fc',
  },
  rose: {
    '--color-bg': '#1f1115',
    '--color-surface-1': '#2e1a20',
    '--color-surface-2': '#4d2d36',
    '--color-surface-3': '#6d404c',
    '--color-surface-inset': '#1a0d11',
    '--color-text-primary': '#ffe4e6',
    '--color-text-secondary': '#fecdd3',
    '--color-text-tertiary': '#fda4af',
    '--color-text-placeholder': '#fb7185',
    '--color-border': '#4d2d36',
    '--color-primary': '#f43f5e',
    '--color-primary-hover': '#e11d48',
    '--color-primary-focus': '#f43f5e',
    '--color-primary-text': '#ffffff',
    '--color-secondary': '#f43f5e', // Re-using for now
    '--color-success': '#22c55e',
    '--color-success-hover': '#16a34a',
    '--color-danger': '#ef4444',
    '--color-warning-border': '#f59e0b',
    '--color-warning-bg': '#b45309',
    '--color-warning-text': '#fef3c7',
    '--color-quota-border': '#f97316',
    '--color-quota-bg': '#c2410c',
    '--color-quota-text': '#ffedd5',
    '--color-error-border': '#dc2626',
    '--color-error-bg': '#991b1b',
    '--color-error-text': '#fecaca',
    '--color-info-border': '#14b8a6',
    '--color-info-bg': '#115e59',
    '--color-info-text': '#ccfbf1',
    '--gradient-from': '#ffe4e6',
    '--gradient-to': '#fda4af',
  }
};
